const productDatas = [
    {
        id: 1,
        name: "Organic Cauliflower",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 4,
        discount: "-27%",
        type: "vegetable",
        image: "/images/all-products/veg2.png",
        nutritionFacts:"Vitamin C and D, Calories 146",
        description: "Cauliflower contains vitamins C and D and only 25 calories, 5 grams of carbohydrates and 2 grams of dietary fiber."
    },
    {
        id: 2,
        name: "Organic Mushroom",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 4,
        discount: "-27%",
        type: "vegetable",
        image: "/images/all-products/veg3.png",
        nutritionFacts:"Vitamin B and Copper, Calories 15",
        description: "Mushrooms (70g) provides 15 calories, 2.2g of protein, and 0.2g of fat. Mushrooms are a good source of copper, B vitamins"
    },
    {
        id: 3,
        name: "Organic Beetroot",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 4,
        discount: "-27%",
        type: "vegetable",
        image: "/images/all-products/veg4.png",
        nutritionFacts:"Vitamin C and D, Calories 58",
        description: "Beetroots are a great source of fiber, folate (vitamin B9), manganese, potassium, iron, and vitamin C."
    },
    {
        id: 4,
        name: "Organic Tomato",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 4,
        discount: "-27%",
        type: "vegetable",
        image: "/images/all-products/veg5.png",
        nutritionFacts:"Vitamin C and K1, Calories 46",
        description: "Tomatoes are a good source of vitamins C, vitamin K1, vitamin B9 and minerals  is beneficial for blood pressure control and heart disease prevention"
    },
    {
        id: 5,
        name: "Organic Capsicum",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 4,
        discount: "-27%",
        type: "vegetable",
        image: "/images/all-products/veg6.png",
        nutritionFacts:"Vitamin B and Iron, Calories 146",
        description: "Capsicum is rich in various antioxidant properties especially carotenoids which are present in ripe specimens of the vegetable."
    },
    {
        id: 6,
        name: "Organic Corn",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 4,
        discount: "-27%",
        type: "vegetable",
        image: "/images/all-products/veg.png",
        nutritionFacts:"Vitamin A and Protien, Calories 46",
        description: "Organic Sweet Corn (1 bag) contains 17g total carbs, 14g net carbs, 1g fat, 0g protein, and 70 calories."
    },
    {
        id: 7,
        name: "Organic Strawberry",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "fruit",
        image: "/images/all-products/fruit.png",
        nutritionFacts:"Vitamin K1 and D, Calories 56",
        description: "Organic strawberries contains 0 g of fat, 1 g of protein, 11 g of carbohydrate and45 calories "
    },
    {
        id: 8,
        name: "Organic Cherry",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "fruit",
        image: "/images/all-products/fruit2.png",
        nutritionFacts:"Vitamin C and B6, Calories 140",
        description: "Cherries are a good source of: Vitamin B6. Potassium and vitamin C  for Boosting Heart Health."
    },
    {
        id: 9,
        name: "Organic Orange",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "fruit",
        image: "/images/all-products/fruit3.png",
        nutritionFacts:"Vitamin C and fiber, Calories 126",
        description: " Oranges are a good source of fiber and a rich source of vitamin C and folate, among many other beneficial nutrients."
    },
    {
        id: 10,
        name: "Organic Mango",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "fruit",
        image: "/images/all-products/fruit4.png",
        nutritionFacts:"Vitamin C and minerals, Calories 126",
        description: "Mango is rich in vitamins, minerals, and antioxidants, including potential anticancer effects, as well as improved immunity and digestive and eye health."
    },
    {
        id: 11,
        name: "Organic Capsicum",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "fruit",
        image: "/images/all-products/fruit5.png",
        nutritionFacts:"Vitamin D and B1, Calories 76",
        description: "Capsicum is rich in various antioxidant properties especially carotenoids which are present in ripe specimens of the vegetable."
    },
    {
        id: 12,
        name: "Organic Tomato",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "fruit",
        image: "/images/all-products/fruit6.png",
        nutritionFacts:"Vitamin A and B9, Calories 143",
        description:"Tomatoes are a good source of vitamins C, vitamin K1, vitamin B9 and minerals  is beneficial for blood pressure control and heart disease prevention"
    },
    {
        id: 13,
        name: "Crunchy bread",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "bread",
        image: "/images/all-products/crunchy-bread.jpg",
        nutritionFacts:"Vitamin C and Iron, Calories 46",
        description: "Bread provides several nutrients such as sugar, protein, iron, calcium and a variety of vitamins "
    },
    {
        id: 14,
        name: "Bread isolated",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "bread",
        image: "/images/all-products/bread-isolated.jpg",
        nutritionFacts:"Vitamin B and Iron, Calories 86",
        description: "Bread provides several nutrients such as sugar, protein, iron, calcium and a variety of vitamins. "
    },
    {
        id: 15,
        name: "Baked croissant",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "bread",
        image: "/images/all-products/fbaked-croissant.jpg",
        nutritionFacts:"Vitamin C and D, Calories 146",
        description: "Bread provides several nutrients such as sugar, protein, iron, calcium and a variety of vitamins. "
    },
    {
        id: 16,
        name: "Fresh bread",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "bread",
        image: "/images/all-products/fresh-bread.jpg",
        nutritionFacts:"Vitamin C and Protien, Calories 146",
        description: "Bread provides several nutrients such as sugar, protein, iron, calcium and a variety of vitamins. "
    },
    {
        id: 17,
        name: "Wheat bread",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "bread",
        image: "/images/all-products/homemade-bread.jpg",
        nutritionFacts:"Vitamin A and E, Calories 46",
        description: "Bread provides several nutrients such as sugar, protein, iron, calcium and a variety of vitamins. "
    },
    {
        id: 18,
        name: "Sliced-bread",
        prevPrice: "$65.00",
        currentPrice: "$50.00",
        ratings: 5,
        discount: "-17%",
        type: "bread",
        image: "/images/all-products/sliced-bread.jpg",
        nutritionFacts:"Vitamin K1 and D, Calories 86",
        description: "Bread provides several nutrients such as sugar, protein, iron, calcium and a variety of vitamins. "
    }
]

export default productDatas